//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordFrequencyNET.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProcessTextAsync", ReplyAction="http://tempuri.org/IService1/ProcessTextAsyncResponse")]
        System.Collections.Generic.Dictionary<string, int> ProcessTextAsync(string content, string splitSymbols);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProcessTextAsync", ReplyAction="http://tempuri.org/IService1/ProcessTextAsyncResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> ProcessTextAsyncAsync(string content, string splitSymbols);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WordFrequencyNET.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WordFrequencyNET.ServiceReference1.IService1>, WordFrequencyNET.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, int> ProcessTextAsync(string content, string splitSymbols) {
            return base.Channel.ProcessTextAsync(content, splitSymbols);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> ProcessTextAsyncAsync(string content, string splitSymbols) {
            return base.Channel.ProcessTextAsyncAsync(content, splitSymbols);
        }
    }
}
